### PR TITLE
Update MCAuth.java

### PR DESCRIPTION
**Pull request by DieneueWelt**
fix unknown word

### CODE REVIEW

**Comment by 4oi** [comment]
The word `pJaupi` is well-known in kotaserver.... isn't it?

**Comment by DieneueWelt** [comment]
Even if it is known, only some people in kotaserver discord

**Comment by 4oi** [comment]
The others may not mind what it is 😺

**Comment by DieneueWelt** [comment]
ahhhhhhh😢😢😢

**Pull request closed without merging**
